### ISSUE TITLE
recent conda-forge binary macOS packages are empty

### ISSUE THREAD

**Issue by lparkes** [conda-forge/configurable-http-proxy-feedstock#27]
Issue:

The binary macOS packages for configurable-http-proxy listed at https://anaconda.org/conda-forge/configurable-http-proxy/files that have been built this year (in 2019) don't have any files in them. If you look at the files sizes, you will see the two most recent osx-64 packages have a file size of 3.6 kB while the other binary packages are almost 1 MB in size.

I have no idea how to reproduce this problem because when I cloned this repo and built the package locally, everything seemed to work fine.

<br/>
Environment (<code>conda list</code>): N/A
<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ): N/A

**Comment by jcrist** [comment]
I also just ran into this. ccing the current recipe owners (@minrk, @willingc).

**Comment by willingc** [comment]
@minrk Any idea why the osx build is so small? It looks like only the `info` folder but not `lib` and `bin` are being stored for osx on Anaconda.

**Comment by willingc** [comment]
Whelp, the merge of #26 now has the Windows and OSX versions with small file sizes. Guessing that we may need #25 to be updated and merged.

**Comment by willingc** [comment]
@minrk #25 fixed OSX but Windows on all 3 node versions is still at 3.7kb.

**Comment by willingc** [comment]
Looks like the Azure Pipelines Windows is erroring in the `conda build setup` step.
